# This file was generated by the `rspec --init` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# Require this file using `require "spec_helper.rb"` to ensure that it is only
# loaded once.
#
# See http://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration
require 'rubygems'
require 'selenium-webdriver'
require 'capybara'
require 'capybara/rspec'
require 'yaml'
require 'rspec'
require 'rest-client'
require 'site_prism'
require 'require_all'
require 'exifr'
require "rexml/document"
require 'logger'
require_all 'Pages'

#Read config file
config_file = "Config/config.yaml"
get_config = YAML.load_file(config_file)

# Start Browser
Capybara::Selenium::Driver.new(:browser =>  get_config['browser'].to_sym)
Capybara.app_host = get_config['url']
Capybara.default_driver = :selenium
Capybara.run_server = false
Capybara.default_wait_time=30

module WaitForAjax
  def wait_for_ajax
    Timeout.timeout(Capybara.default_wait_time) do
      loop until finished_all_ajax_requests?
    end
  end

  def finished_all_ajax_requests?
    page.evaluate_script('jQuery.active').zero?
  end
end

RSpec.configure do |config|
config.include Capybara::DSL
config.include WaitForAjax, type: :feature
end

#Get image attribute from Flickr API
def get_api_camera_attribute(api_url, api_key,photo_id)
  url = "#{api_url}&api_key=#{api_key}&photo_id=#{photo_id}"
  resp = RestClient.get(url)
  doc = REXML::Document.new(resp)
  api_camera_value= doc.root.elements[1].attributes['camera']
  return api_camera_value
end

#Get title attribute from Flickr API
def get_api_title_attribute(api_url, api_key,photo_id)
  url = "#{api_url}&api_key=#{api_key}&photo_id=#{photo_id}"
  resp = RestClient.get(url)
  doc = REXML::Document.new(resp)
  api_camera_value= doc.root.elements[1].elements['title'].text
  return api_camera_value
end